CREATE TABLE Addresses
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	StateId INTEGER DEFAULT 0,
	Label TEXT NOT NULL
);

CREATE TABLE Categories
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	parentId INTEGER DEFAULT NULL,
	FOREIGN KEY(parentId) REFERENCES Categories(id)
);

CREATE TABLE Contacts
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	addressId INTEGER DEFAULT NULL,
	Label TEXT NOT NULL,
	FOREIGN KEY(addressId) REFERENCES Addresses(id)
);

CREATE TABLE Makers
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE Sections
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	categoryId INTEGER DEFAULT NULL,
	makerId INTEGER DEFAULT NULL,
	Label TEXT NOT NULL,
	FOREIGN KEY(categoryId) REFERENCES Categories(id),
	FOREIGN KEY(makerId) REFERENCES Makers(id)
);

CREATE TABLE Series
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	makerId INTEGER DEFAULT NULL,
	Label TEXT NOT NULL,
	FOREIGN KEY(makerId) REFERENCES Makers(id)
);

CREATE TABLE Products
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	makerId INTEGER DEFAULT NULL,
	sectionId INTEGER DEFAULT NULL,
	seriesId INTEGER DEFAULT NULL,
	Label TEXT NOT NULL,
	FOREIGN KEY(makerId) REFERENCES Makers(id),
	FOREIGN KEY(sectionId) REFERENCES Sections(id),
	FOREIGN KEY(seriesId) REFERENCES Series(id)
);
