CREATE TABLE "Addresses"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"stateId" INTEGER DEFAULT 0,
	"label" TEXT NOT NULL
);

CREATE TABLE "Categories"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" TEXT NOT NULL,
	"parentId" INTEGER,
	CONSTRAINT "FK_Categories_0_0" FOREIGN KEY("parentId") REFERENCES "Categories"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Contacts"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"addressId" INTEGER,
	"label" TEXT NOT NULL,
	CONSTRAINT "FK_Contacts_0_0" FOREIGN KEY("addressId") REFERENCES "Addresses"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Makers"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" TEXT NOT NULL
);

CREATE TABLE "Sections"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"categoryId" INTEGER,
	"makerId" INTEGER,
	"label" TEXT,
	CONSTRAINT "FK_Sections_1_0" FOREIGN KEY("categoryId") REFERENCES "Categories"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT "FK_Sections_0_0" FOREIGN KEY("makerId") REFERENCES "Makers"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Series"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"makerId" INTEGER,
	"label" TEXT NOT NULL,
	CONSTRAINT "FK_Series_0_0" FOREIGN KEY("makerId") REFERENCES "Makers"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Products"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"makerId" INTEGER,
	"sectionId" INTEGER,
	"seriesId" INTEGER,
	"label" TEXT,
	CONSTRAINT "FK_Products_2_0" FOREIGN KEY("makerId") REFERENCES "Makers"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT "FK_Products_1_0" FOREIGN KEY("sectionId") REFERENCES "Sections"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT "FK_Products_0_0" FOREIGN KEY("seriesId") REFERENCES "Series"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
