CREATE TABLE "Addresses"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"stateId" INTEGER DEFAULT 0,
	"label" TEXT NOT NULL
);

CREATE TABLE "Categories"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" TEXT NOT NULL,
	"parentId" INTEGER,
	CONSTRAINT "CategoriesParents" FOREIGN KEY("parentId") REFERENCES "Categories"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Contacts"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"addressId" INTEGER,
	"label" TEXT NOT NULL,
	CONSTRAINT "ContactsAddresses" FOREIGN KEY("addressId") REFERENCES "Addresses"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Makers"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" TEXT NOT NULL
);

CREATE TABLE "Sections"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"categoryId" INTEGER,
	"makerId" INTEGER,
	"label" TEXT,
	CONSTRAINT "SectionsCategories" FOREIGN KEY("categoryId") REFERENCES "Categories"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT "SectionsMakers" FOREIGN KEY("makerId") REFERENCES "Makers"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Series"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"makerId" INTEGER,
	"label" TEXT NOT NULL,
	CONSTRAINT "SeriesMakers" FOREIGN KEY("makerId") REFERENCES "Makers"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Products"
(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"makerId" INTEGER,
	"sectionId" INTEGER,
	"seriesId" INTEGER,
	"label" TEXT,
	CONSTRAINT "ProductsMakers" FOREIGN KEY("makerId") REFERENCES "Makers"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT "ProductsSections" FOREIGN KEY("sectionId") REFERENCES "Sections"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT "ProductsSeries" FOREIGN KEY("seriesId") REFERENCES "Series"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
