CREATE TABLE [Addresses]
(
	id AUTOINCREMENT PRIMARY KEY,
	[StateId] INTEGER DEFAULT 0,
	[Label] VARCHAR(50) WITH COMPRESSION
);

CREATE TABLE `Categories`
(
	id AUTOINCREMENT PRIMARY KEY,
	`name` VARCHAR(50) WITH COMPRESSION
);

CREATE TABLE `Contacts`
(
	id AUTOINCREMENT PRIMARY KEY,
	idAddresses INTEGER DEFAULT NULL
		CONSTRAINT FK_Contacts REFERENCES Addresses (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	[Label] VARCHAR(50) WITH COMPRESSION
);

CREATE TABLE `Makers`
(
	id AUTOINCREMENT PRIMARY KEY,
	`name` VARCHAR(50) WITH COMPRESSION
);

CREATE TABLE `Sections`
(
	id AUTOINCREMENT PRIMARY KEY,
	categoryId INTEGER DEFAULT NULL
		CONSTRAINT SectionsCategories REFERENCES Categories (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	makerId INTEGER DEFAULT NULL
		CONSTRAINT SectionsMakers REFERENCES Makers (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	[Label] VARCHAR(50) WITH COMPRESSION
);

CREATE TABLE `Series`
(
	id AUTOINCREMENT PRIMARY KEY,
	makerId INTEGER DEFAULT NULL
		CONSTRAINT SeriesMakers REFERENCES Makers (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	[Label] VARCHAR(50) WITH COMPRESSION
);

CREATE TABLE `Products`
(
	id AUTOINCREMENT PRIMARY KEY,
	makerId INTEGER DEFAULT NULL
		CONSTRAINT ProductsMakers REFERENCES Makers (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	sectionId INTEGER DEFAULT NULL
		CONSTRAINT ProductsSections REFERENCES Sections (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	seriesId INTEGER DEFAULT NULL
		CONSTRAINT ProductsSeries REFERENCES Series (id)
		ON DELETE SET NULL ON UPDATE CASCADE,
	[Label] VARCHAR(50) WITH COMPRESSION
);
